server:
  port: ${SERVER_PORT}
  compression: # 压缩配置
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json

#配置web页面入口
magic-api:
  web: /magic/web
  resource:
    #location: /data/magic-api
    type: database
    table-name: magic_api_file
  auto-import-module: db,log
  security:
    username: wsj
    password: 123
  #prefix: /magic # 因为框架对没有接口请求使用验证的，所有加了前缀，配置magic开头的请求都不需要验证
  editor-config: classpath:./magic-editor.js # 编辑器配置
  persistence-response-body: false
  thread-pool-executor-size: 50
  backup:
    enable: true # 是否开启备份功能
    max-history: -1
    table-name: magic_backup_record_v2
  sql-column-case: camel


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}